name: Complex
on: push

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - run: date
    - run: printenv
  windows:
    runs-on: windows-latest
    steps:
    - run: date
    - run: gci env: | sort name
  macos: 
    runs-on: macos-latest
    steps:
    - run: date
    - run: env
  phunkydepends:
    needs: [ubuntu, windows, macos]
    runs-on: macos-latest
    steps:
    - run: date
    - run: printenv
    - run: echo "This is the last runner completing..."
